config/routes.rb
Rails.application.routes.draw do
  resources :services
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :membres
  # Defines the root path route ("/")
  root "membres#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/fanome.rb
class Fanome < ApplicationRecord
end

app/models/membre.rb
class Membre < ApplicationRecord
end

app/models/service.rb
class Service < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/membres_controller.rb
class MembresController < ApplicationController
  before_action :set_membre, only: %i[ show edit update destroy ]

  # GET /membres
  def index
    @membres = Membre.all
  end

  # GET /membres/1
  def show
  end

  # GET /membres/new
  def new
    @membre = Membre.new
  end

  # GET /membres/1/edit
  def edit
  end

  # POST /membres
  def create
    @membre = Membre.new(membre_params)

    if @membre.save
      redirect_to @membre, notice: "Membre was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /membres/1
  def update
    if @membre.update(membre_params)
      redirect_to @membre, notice: "Membre was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /membres/1
  def destroy
    @membre.destroy
    redirect_to membres_url, notice: "Membre was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_membre
      @membre = Membre.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def membre_params
      params.require(:membre).permit(:mbID, :fiantso, :anarana, :fanampiny, :tsyeo, :fanamarih)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: %i[ show edit update destroy ]

  # GET /services
  def index
    @services = Service.all
  end

  # GET /services/1
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    if @service.save
      redirect_to @service, notice: "Service was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: "Service was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: "Service was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def service_params
      params.require(:service).permit(:fohy, :lava, :fanamarih)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/membres_helper.rb
module MembresHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FanompoanaRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/membres/_form.html.erb
<%= form_with(model: membre) do |form| %>
  <% if membre.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(membre.errors.count, "error") %> prohibited this membre from being saved:</h2>

      <ul>
        <% membre.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :mbID, style: "display: block" %>
    <%= form.number_field :mbID %>
  </div>

  <div>
    <%= form.label :fiantso, style: "display: block" %>
    <%= form.text_field :fiantso %>
  </div>

  <div>
    <%= form.label :anarana, style: "display: block" %>
    <%= form.text_field :anarana %>
  </div>

  <div>
    <%= form.label :fanampiny, style: "display: block" %>
    <%= form.text_field :fanampiny %>
  </div>

  <div>
    <%= form.label :tsyeo, style: "display: block" %>
    <%= form.check_box :tsyeo %>
  </div>

  <div>
    <%= form.label :fanamarih, style: "display: block" %>
    <%= form.text_area :fanamarih %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/membres/_membre.html.erb
<div id="<%= dom_id membre %>">
  <p>
    <strong>Mbid:</strong>
    <%= membre.mbID %>
  </p>

  <p>
    <strong>Fiantso:</strong>
    <%= membre.fiantso %>
  </p>

  <p>
    <strong>Anarana:</strong>
    <%= membre.anarana %>
  </p>

  <p>
    <strong>Fanampiny:</strong>
    <%= membre.fanampiny %>
  </p>

  <p>
    <strong>Tsyeo:</strong>
    <%= membre.tsyeo %>
  </p>

  <p>
    <strong>Fanamarih:</strong>
    <%= membre.fanamarih %>
  </p>

</div>

app/views/membres/edit.html.erb
<h1>Editing membre</h1>

<%= render "form", membre: @membre %>

<br>

<div>
  <%= link_to "Show this membre", @membre %> |
  <%= link_to "Back to membres", membres_path %>
</div>

app/views/membres/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Membres</h1>

<div id="membres">
  <% @membres.each do |membre| %>
    <%= render membre %>
    <p>
      <%= link_to "Show this membre", membre %>
    </p>
  <% end %>
</div>

<%= link_to "New membre", new_membre_path %>

app/views/membres/new.html.erb
<h1>New membre</h1>

<%= render "form", membre: @membre %>

<br>

<div>
  <%= link_to "Back to membres", membres_path %>
</div>

app/views/membres/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @membre %>

<div>
  <%= link_to "Edit this membre", edit_membre_path(@membre) %> |
  <%= link_to "Back to membres", membres_path %>

  <%= button_to "Destroy this membre", @membre, method: :delete %>
</div>

app/views/services/_form.html.erb
<%= form_with(model: service) do |form| %>
  <% if service.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
        <% service.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :fohy, style: "display: block" %>
    <%= form.text_field :fohy %>
  </div>

  <div>
    <%= form.label :lava, style: "display: block" %>
    <%= form.text_field :lava %>
  </div>

  <div>
    <%= form.label :fanamarih, style: "display: block" %>
    <%= form.text_field :fanamarih %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/services/_service.html.erb
<div id="<%= dom_id service %>">
  <p>
    <strong>Fohy:</strong>
    <%= service.fohy %>
  </p>

  <p>
    <strong>Lava:</strong>
    <%= service.lava %>
  </p>

  <p>
    <strong>Fanamarih:</strong>
    <%= service.fanamarih %>
  </p>

</div>

app/views/services/edit.html.erb
<h1>Editing service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Show this service", @service %> |
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Services</h1>

<div id="services">
  <% @services.each do |service| %>
    <%= render service %>
    <p>
      <%= link_to "Show this service", service %>
    </p>
  <% end %>
</div>

<%= link_to "New service", new_service_path %>

app/views/services/new.html.erb
<h1>New service</h1>

<%= render "form", service: @service %>

<br>

<div>
  <%= link_to "Back to services", services_path %>
</div>

app/views/services/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @service %>

<div>
  <%= link_to "Edit this service", edit_service_path(@service) %> |
  <%= link_to "Back to services", services_path %>

  <%= button_to "Destroy this service", @service, method: :delete %>
</div>